version: "3"
services:
  app:
    build: .
    tty: true
    command: node /app/extract-pdf-annotations.js "/input/[INPUT]"
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - [SOURCE]:/input/