version: "3"
services:
  app:
    image: pudding/docker-app:docker-app-iclass-pdf-scoring-20231125.144834
    command: node /app/index.js "/input/__INPUT__"
    tty: true
    environment:
      - LOCAL_VOLUMN_PATH=/input/
      - CONTAINER_NAME=docker-app-iclass-pdf-scoring-app
      - RUN_COMMAND=node /app/index.js
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - __SOURCE__:/input/
      - __SOURCE__:/output/